// src/app/about/page.tsx
export default function AboutPage() {
  return (
    <div className="relative py-16 bg-white overflow-hidden">
      <div className="hidden lg:block lg:absolute lg:inset-y-0 lg:h-full lg:w-full" />
      <div className="relative px-4 sm:px-6 lg:px-8">
        <div className="text-lg max-w-prose mx-auto">
          <h1>
            <span className="block text-base text-center text-primary font-semibold tracking-wide uppercase">
              About
            </span>
            <span className="mt-2 block text-3xl text-center leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl">
              International China Studies Events Clearing-house
            </span>
          </h1>
          <div className="mt-6 prose prose-indigo prose-lg text-gray-500 mx-auto">
            <p>
              In spring 2020, as a result of the Covid-19 pandemic, China
              Studies around the world moved online. One unanticipated
              consequence of this unfortunate situation is that it has become
              possible to attend events regardless of one&apos;s location. The
              International China Studies Events Clearing-house has been created
              to share information about upcoming online events with the broader
              China studies community. The Clearing-house is maintained by the
              Fairbank Center for Chinese Studies at Harvard University. It was
              built by Kwok-Leong Tang, Digital China Fellow at the Fairbank
              Center. We rely on our colleagues around the world to include
              their upcoming events; the catalog is not intended to be
              comprehensive. The Fairbank Center provides this clearing-house as
              a service to the field. We do not take responsibility for any of
              the events listed here, and unfortunately cannot respond to
              queries. Please contact the organizer of the specific event
              directly. We hope you find this catalog helpful.
            </p>
          </div>
          <div className="text-lg max-w-prose mx-auto py-8">
            <h1>
              <span className="mt-2 block text-3xl text-center leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl">
                國際中國研究活動資訊交換中心
              </span>
              <span className="block text-base text-center text-primary font-semibold tracking-wide uppercase pt-4">
                緣起
              </span>
            </h1>
          </div>
          <p>
            庚子年（2020）春，大疫流行，全球各地的中國研究活動紛紛轉移網上。如今參加活動不再受地域所限，亦屬不幸中始料不及的結果。
            國際中國研究網上活動資訊交換中心旨在與廣大的中國研究社群分享即將舉辦的活動。
            本網站由哈佛大學費正清中國研究中心維護，數碼中國研究員鄧國亮建置。
            我們有賴世界各地的同行提供活動資訊，但本目錄並不以無所不包爲目標。
            本網站乃費正清中國研究中心為中國研究同寅所提供之服務，本中心對所刊登之活動並無任何責任，亦不會回應任何活動查詢。
            如對活動有所疑問，請直接與活動主辦人聯絡。 我們希望本目錄爲您帶來便利。
          </p>
        </div>
      </div>
    </div>
  );
}

// src/pages/About.vue
<template>
  <layout>
    <div class="relative py-16 bg-white overflow-hidden">
      <div class="hidden lg:block lg:absolute lg:inset-y-0 lg:h-full lg:w-full">
      </div>
      <div class="relative px-4 sm:px-6 lg:px-8">
        <div class="text-lg max-w-prose mx-auto">
          <h1>
            <span
              class="block text-base text-center text-primary font-semibold tracking-wide uppercase"
              >About</span
            >
            <span
              class="mt-2 block text-3xl text-center leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl"
              >International China Studies Events Clearing-house</span
            >
          </h1>
        <div class="mt-6 prose prose-indigo prose-lg text-gray-500 mx-auto">
          <p>In spring 2020, as a result of the Covid-19 pandemic, China Studies around the world moved online. 
            One unanticipated consequence of this unfortunate situation is that it has become possible to attend events regardless of one's location. 
            The International China Studies Events Clearing-house has been created to share information about upcoming online events with the broader China studies community.
            The Clearing-house is maintained by the Fairbank Center for Chinese Studies at Harvard University.   It was built by Kwok-Leong Tang, Digital China Fellow at the Fairbank Center.  
            We rely on our colleagues around the world to include their upcoming events; the catalog is not intended to be comprehensive. The Fairbank Center provides this clearing-house as a service to the field. We do not take responsibility for any of the events listed here, and unfortunately cannot respond to queries. Please contact the organizer of the specific event directly. We hope you find this catalog helpful.
          </p>
        </div>
                  <div class="text-lg max-w-prose mx-auto py-8">
          <h1>

            <span
              class="mt-2 block text-3xl text-center leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl"
              >國際中國研究活動資訊交換中心</span
            >
           <span
              class="block text-base text-center text-primary font-semibold tracking-wide uppercase pt-4"
              >緣起</span
            >
          </h1>
        </div>
          <p>
            庚子年（2020）春，大疫流行，全球各地的中國研究活動紛紛轉移網上。如今參加活動不再受地域所限，亦屬不幸中始料不及的結果。
            國際中國研究網上活動資訊交換中心旨在與廣大的中國研究社群分享即將舉辦的活動。
            本網站由哈佛大學費正清中國研究中心維護，數碼中國研究員鄧國亮建置。
            我們有賴世界各地的同行提供活動資訊，但本目錄並不以無所不包爲目標。
            本網站乃費正清中國研究中心為中國研究同寅所提供之服務，本中心對所刊登之活動並無任何責任，亦不會回應任何活動查詢。
            如對活動有所疑問，請直接與活動主辦人聯絡。
            我們希望本目錄爲您帶來便利。
          </p>
        </div>
      </div>
    </div>
    </div>
  </layout>
</template>
